from enum import Enum


class ErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST"
    NOT_FOUND = "NOOT_FOUND"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
