/* tslint:disable */
/* eslint-disable */
/**
 * KayBot
 * KayBot is a chatbot that can be utilized for lead generation in the field of digital marketing.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 *
 * @export
 * @interface ChatCompletionChoice
 */
export interface ChatCompletionChoice {
  /**
   *
   * @type {any}
   * @memberof ChatCompletionChoice
   */
  index: any;
  /**
   *
   * @type {ChatCompletionChoiceMessage}
   * @memberof ChatCompletionChoice
   */
  message: ChatCompletionChoiceMessage;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionChoice
   */
  finish_reason: any;
}
/**
 *
 * @export
 * @interface ChatCompletionChoiceMessage
 */
export interface ChatCompletionChoiceMessage {
  /**
   *
   * @type {ChatCompletionRoleEnum}
   * @memberof ChatCompletionChoiceMessage
   */
  role: ChatCompletionRoleEnum;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionChoiceMessage
   */
  content: any;
}

/**
 *
 * @export
 * @interface ChatCompletionResponse
 */
export interface ChatCompletionResponse {
  /**
   *
   * @type {ChatCompletionResponseBody}
   * @memberof ChatCompletionResponse
   */
  response: ChatCompletionResponseBody;
}
/**
 *
 * @export
 * @interface ChatCompletionResponseBody
 */
export interface ChatCompletionResponseBody {
  /**
   *
   * @type {any}
   * @memberof ChatCompletionResponseBody
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionResponseBody
   */
  object: any;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionResponseBody
   */
  created: any;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionResponseBody
   */
  model: any;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionResponseBody
   */
  choices: any;
  /**
   *
   * @type {ChatCompletionUsage}
   * @memberof ChatCompletionResponseBody
   */
  usage: ChatCompletionUsage;
}
/**
 *
 * @export
 * @interface ChatCompletionRoleEnum
 */
export interface ChatCompletionRoleEnum {}
/**
 *
 * @export
 * @interface ChatCompletionUsage
 */
export interface ChatCompletionUsage {
  /**
   *
   * @type {any}
   * @memberof ChatCompletionUsage
   */
  prompt_tokens: any;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionUsage
   */
  completion_tokens: any;
  /**
   *
   * @type {any}
   * @memberof ChatCompletionUsage
   */
  total_tokens: any;
}
/**
 *
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
  /**
   *
   * @type {any}
   * @memberof HTTPValidationError
   */
  detail?: any;
}
/**
 *
 * @export
 * @interface MessageSend
 */
export interface MessageSend {
  /**
   *
   * @type {any}
   * @memberof MessageSend
   */
  message_body: any;
}
/**
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
  /**
   *
   * @type {any}
   * @memberof ValidationError
   */
  loc: any;
  /**
   *
   * @type {any}
   * @memberof ValidationError
   */
  msg: any;
  /**
   *
   * @type {any}
   * @memberof ValidationError
   */
  type: any;
}

/**
 * ChatApi - axios parameter creator
 * @export
 */
export const ChatApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * An endpoint to post messages and expect a response. The messages are reconstructed into a valuable prompt and sent over to OpenAI\'s API which most likely responds with a message.  :param message: The message object containing the message body to send  Raises:     HTTPException
     * @summary Chat
     * @param {MessageSend} messageSend
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    chatChatMessagePost: async (messageSend: MessageSend, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'messageSend' is not null or undefined
      assertParamExists('chatChatMessagePost', 'messageSend', messageSend);
      const localVarPath = `/chat/message`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(messageSend, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ChatApi - functional programming interface
 * @export
 */
export const ChatApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ChatApiAxiosParamCreator(configuration);
  return {
    /**
     * An endpoint to post messages and expect a response. The messages are reconstructed into a valuable prompt and sent over to OpenAI\'s API which most likely responds with a message.  :param message: The message object containing the message body to send  Raises:     HTTPException
     * @summary Chat
     * @param {MessageSend} messageSend
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async chatChatMessagePost(
      messageSend: MessageSend,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatCompletionResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.chatChatMessagePost(messageSend, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * ChatApi - factory interface
 * @export
 */
export const ChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = ChatApiFp(configuration);
  return {
    /**
     * An endpoint to post messages and expect a response. The messages are reconstructed into a valuable prompt and sent over to OpenAI\'s API which most likely responds with a message.  :param message: The message object containing the message body to send  Raises:     HTTPException
     * @summary Chat
     * @param {ChatApiChatChatMessagePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    chatChatMessagePost(
      requestParameters: ChatApiChatChatMessagePostRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<ChatCompletionResponse> {
      return localVarFp
        .chatChatMessagePost(requestParameters.messageSend, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for chatChatMessagePost operation in ChatApi.
 * @export
 * @interface ChatApiChatChatMessagePostRequest
 */
export interface ChatApiChatChatMessagePostRequest {
  /**
   *
   * @type {MessageSend}
   * @memberof ChatApiChatChatMessagePost
   */
  readonly messageSend: MessageSend;
}

/**
 * ChatApi - object-oriented interface
 * @export
 * @class ChatApi
 * @extends {BaseAPI}
 */
export class ChatApi extends BaseAPI {
  /**
   * An endpoint to post messages and expect a response. The messages are reconstructed into a valuable prompt and sent over to OpenAI\'s API which most likely responds with a message.  :param message: The message object containing the message body to send  Raises:     HTTPException
   * @summary Chat
   * @param {ChatApiChatChatMessagePostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ChatApi
   */
  public chatChatMessagePost(requestParameters: ChatApiChatChatMessagePostRequest, options?: AxiosRequestConfig) {
    return ChatApiFp(this.configuration)
      .chatChatMessagePost(requestParameters.messageSend, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * RootApi - axios parameter creator
 * @export
 */
export const RootApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rootGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RootApi - functional programming interface
 * @export
 */
export const RootApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RootApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rootGet(
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * RootApi - factory interface
 * @export
 */
export const RootApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = RootApiFp(configuration);
  return {
    /**
     *
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rootGet(options?: AxiosRequestConfig): AxiosPromise<any> {
      return localVarFp.rootGet(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * RootApi - object-oriented interface
 * @export
 * @class RootApi
 * @extends {BaseAPI}
 */
export class RootApi extends BaseAPI {
  /**
   *
   * @summary Root
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApi
   */
  public rootGet(options?: AxiosRequestConfig) {
    return RootApiFp(this.configuration)
      .rootGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
